name: Build and Push App image to GCP AR
on: 
  push:
    branches:
      - main
      - develop

jobs:
  prep-env:
    runs-on: ubuntu-latest
    name: Env prep
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: GCP auth 
        uses: google-github-actions/auth@v0 # https://github.com/google-github-actions/setup-gcloud/blob/master/README.md
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0 # https://github.com/google-github-actions/setup-gcloud/blob/master/README.md

      - name: Use gcloud CLI
        run: gcloud info

  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push testapp Docker image
    env:
      IMAGE_NAME: testapp
      PROJECT_ID: lauri-container-fundamentals
    steps:
      - name: Build DEV testapp Docker image
        if: github.ref == 'refs/heads/develop'
        run: docker build -t $IMAGE_NAME:$GITHUB_JOB .

      - name: Build latest testapp Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker client
        run: |-
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Push DEV Docker image to GCP AR
        if: github.ref == 'refs/heads/develop'
        run: |-
          docker tag $IMAGE_NAME:latest europe-north1-docker.pkg.dev/$PROJECT_ID/fleuri/$IMAGE_NAME:$GITHUB_JOB
          docker push europe-north1-docker.pkg.dev/$PROJECT_ID/fleuri/$IMAGE_NAME:$GITHUB_JOB

      - name: Push latest Docker image to GCP AR
        if: github.ref == 'refs/heads/main'
        run: |-
          docker tag $IMAGE_NAME:latest europe-north1-docker.pkg.dev/$PROJECT_ID/fleuri/$IMAGE_NAME:latest
          docker push europe-north1-docker.pkg.dev/$PROJECT_ID/fleuri/$IMAGE_NAME:latest