name: Build and Push App image to GCP AR

on: 
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

env:
  IMAGE_NAME: testapp
  PROJECT_ID: lauri-container-fundamentals
  DOCKER_REGISTRY: europe-north1-docker.pkg.dev
  K8S_DEV_DEPLOYMENT_MANIFEST_PATH: kubernetes/dev/testapp-deployment.yaml
  K8S_PROD_DEPLOYMENT_MANIFEST_PATH: kubernetes/prod/testapp-deployment.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push testapp Docker image
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: GCP auth 
        uses: google-github-actions/auth@v0 # https://github.com/google-github-actions/setup-gcloud/blob/master/README.md
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0 # https://github.com/google-github-actions/setup-gcloud/blob/master/README.md

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker client
        run: |-
          gcloud auth configure-docker $DOCKER_REGISTRY

      # For develop branch
      - name: Build DEV testapp Docker image
        if: github.ref == 'refs/heads/develop'
        run: docker build -t $IMAGE_NAME:$GITHUB_RUN_ID .

      - name: Push DEV Docker image to GCP AR
        if: github.ref == 'refs/heads/develop'
        run: |
          docker tag $IMAGE_NAME:$GITHUB_RUN_ID $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:$GITHUB_RUN_ID
          docker push $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:$GITHUB_RUN_ID

      ## For main branch
      - name: Build latest testapp Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push latest Docker image to GCP AR
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:latest
          docker push $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:latest

      ### For tags
      - name: Build tagged testapp Docker image
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          docker build -t $IMAGE_NAME:$GIT_TAG .

      - name: Push tagged Docker image to GCP AR
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          docker tag $IMAGE_NAME:$GIT_TAG $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:$GIT_TAG
          docker push $DOCKER_REGISTRY/$PROJECT_ID/fleuri/$IMAGE_NAME:$GIT_TAG


  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: [build-and-push] # Identifies any jobs that must complete successfully before this job will run
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      # For develop branch
      - name: Update DEV testapp Docker image version in k8s deployment manifest
        if: github.ref == 'refs/heads/develop'
        run: |
          export OLD_IMAGE=$(cat $K8S_DEV_DEPLOYMENT_MANIFEST_PATH | grep -o "$IMAGE_NAME:[0-9]*" | grep -o "[0-9]*")
          sed -i "s/$OLD_IMAGE/$GITHUB_RUN_ID/g" $K8S_DEV_DEPLOYMENT_MANIFEST_PATH

      ### For tags
      - name: Update tagged testapp Docker image version in k8s deployment manifest
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          export OLD_IMAGE=$(cat $K8S_PROD_DEPLOYMENT_MANIFEST_PATH | grep -o "$IMAGE_NAME:v[0-9].*" | grep -o "v[0-9].*")
          sed -i "s/$OLD_IMAGE/$GIT_TAG/g" $K8S_PROD_DEPLOYMENT_MANIFEST_PATH

      - name: Commit changes in manifests
        run: |
          git config --global user.name 'Github Actions CI'
          git config --global user.email 'github.actions@users.noreply.github.com'
          git add kubernetes
      
      # For develop branch
      - name: Push DEV changes to repo
        if: github.ref == 'refs/heads/develop'
        run: |
          git commit -m "Updated dev manifests version $GITHUB_RUN_ID"
          git push

      ### For tags
      - name: Push tag changes to repo
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          git commit -m "Updated prod manifests version $GIT_TAG"
          git push